package org.personal.domain.exception

class AlreadyFollowingException : RuntimeException("Follow relationship already exists")